### ISSUE TITLE
how to compile then run a bash script?

### ISSUE THREAD

**Issue by m2acgi** [olbat/binsh#1] opened 2018-06-06 07:16 UTC
I have a bash script like this
```
#!/bin/bash

...some command...
```
It no work after complie with `./build.sh sample.sh 123456 sample`. I'am using the Debian linux, as it's default shell is **dash**, not **bash**, so I wanna to compile with **/bin/bash**, then how would I do?

**Comment by olbat** [comment] 2018-06-08 17:19
Hi @m2acgi, you can specify the shell command to be used by _execve_ as the 4th argument of the _build.sh_ script.
I think that `./build.sh sample.sh 123456 sample "/bin/bash -s --"` would work, can you give it a try ?

**Comment by m2acgi** [comment] 2018-10-15 10:35
@olbat 
It still not working.

**Comment by olbat** [comment] 2018-10-15 20:11
Any update? If not I'll close the issue.

**Comment by m2acgi** [comment] 2018-10-16 01:20
@olbat 
It not working with `"/bin/bash -s --"`, working with `/bin/bash -s --`, but when shell script with multiple ssh command, it only execute the first one:

```
ssh root@192.168.1.100 "echo 1"
ssh root@192.168.1.100 "echo 2"
ssh root@192.168.1.100 "echo 3"
```

Output:
```
1
```

**Comment by olbat** [comment] 2018-10-16 20:24
Okay, I think that your issue is not really related to this script but more with [the ssh command itself](https://serverfault.com/search?q=ssh+command+hangs).

You should maybe use [nohup](https://linux.die.net/man/1/nohup), redirect the standard input&outputs, use the `-T` option or close anything that's preventing your ssh command to return ...

Did you try to run your script from bash directly? (if yes, is it hanging?)

**Comment by m2acgi** [comment] 2018-10-17 00:03
It's all ok when run shell script directly.
It's all ok when bilud directly.
There're some ssh issues when bilud with `/bin/bash -s --`.

**Comment by m2acgi** [comment] 2018-10-17 00:07
I must build with `/bin/bash -s --` because some code in my script not compatible with `/bin/dash`, it only compatible with `/bin/bash`.

**Comment by olbat** [comment] 2018-10-18 15:16
I think that it's related to the way both bash and ssh are dealing with standard input&outputs.

I tried to create a small example, got the same issue and managed to get it working using `ssh -n` or adding `</dev/null` after every ssh command.
Can you give it a try?

**Comment by m2acgi** [comment] 2018-10-18 15:44
I've try  the method you mentioned before. It can resolve this issue.

**Comment by m2acgi** [comment] 2018-10-18 15:55
But I wanna to keep my script code clean. So fix the issue in binsh would be ok.

**Comment by olbat** [comment] 2018-10-18 18:34
As I said it before I don't think that the issue is coming from binsh itself, or at least if it does there is nothing I think I can do about it (I want to keep the "pass the a key file from stdin" feature so the executable will continue to deal with the standard input the same way).

Anyway, if you have a good idea about where is this issue is coming from and how to fix it, feel free to open a pull request.

I'll try to find some time to reproduce on Debian this week. After that I'll close this issue if I don't get any news from you since there is a workaround to deal with it.

**Comment by olbat** [comment] 2018-10-18 18:41
Another idea of a workaround if dash is really the issue here: you can try to change the default shell for your user using [chsh](https://linux.die.net/man/1/chsh).

**Comment by m2acgi** [comment] 2018-10-19 00:06
Thank you. I'll try to change the shell from dash to bash.

**Closed as completed** 2018-10-19 00:06 UTC
